name: better_buzz
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.4.0
  firebase_database: ^10.1.0
  go_router: ^7.0.0
  lottie: ^2.6.0
  flutter_native_splash: ^2.2.19
  google_maps_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: "^0.12.0"

flutter:
  assets:
    - assets/logo/
    - assets/lotties/
    - assets/images/
  uses-material-design: true

flutter_icons:
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#1F1B16"

flutter_native_splash:
  color: "#FFFBFF"
  color_dark: "#1F1B16"
  image: "assets/icons/splash_light.png"
  image_dark: "assets/icons/splash_dark.png"
  android: true
  ios: true
